#!/bin/bash

# Invoke Confluence.
cf base_test.cf

fnf -read_fnf out.fnf -write_c out -write_fnf out.fnf

# Compile C.
gcc -Wall -c out.c

# Compile and execute Verilog.
#iverilog -Wall -o lib_unit_test_v lib_unit_test_bench.v lib_unit_test.v
#./lib_unit_test_v

# Compile and execute VHDL.
#ghdl -a lib_unit_test_bench.vhd lib_unit_test.vhd

# Validate XML netlist.
#xmllint -noout -valid lib_unit_test.xml

# Clean up.
#rm out.*
